<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductVariantsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('product_variants')->insert([
            // Bia hơi
            [
                'product_id' => 1,
                'brand' => 'Local Beer',
                'attribute' => 'CHAI 330ML',
                'description' => 'Bia hơi tươi, chai 330ml.',
                'price' => 35000,
                'image' => 'bia_hoi_330ml.jpg',
                'quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'brand' => 'Premium Beer',
                'attribute' => 'CHAI 500ML',
                'description' => 'Bia hơi tươi, chai 500ml.',
                'price' => 45000,
                'image' => 'bia_hoi_500ml.jpg',
                'quantity' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rượu mạnh
            [
                'product_id' => 2,
                'brand' => 'Whiskey Brand',
                'attribute' => 'CHAI 700ML',
                'description' => 'Rượu mạnh, chai 700ml.',
                'price' => 450000,
                'image' => 'ruou_manh_700ml.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'brand' => 'Whiskey Premium',
                'attribute' => 'CHAI 1L',
                'description' => 'Rượu mạnh, chai 1L.',
                'price' => 650000,
                'image' => 'ruou_manh_1l.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rượu champagnes
            [
                'product_id' => 3,
                'brand' => 'Champagnes Brand',
                'attribute' => 'CHAI 750ML',
                'description' => 'Rượu champagnes, chai 750ml.',
                'price' => 550000,
                'image' => 'champane_750ml.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'brand' => 'Champagnes Premium',
                'attribute' => 'CHAI 1L',
                'description' => 'Rượu champagnes, chai 1L.',
                'price' => 700000,
                'image' => 'champane_1l.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rượu vang trắng
            [
                'product_id' => 4,
                'brand' => 'White Wine Brand',
                'attribute' => 'CHAI 750ML',
                'description' => 'Rượu vang trắng, chai 750ml.',
                'price' => 400000,
                'image' => 'ruou_vang_trang_750ml.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'brand' => 'White Wine Premium',
                'attribute' => 'CHAI 1L',
                'description' => 'Rượu vang trắng, chai 1L.',
                'price' => 520000,
                'image' => 'ruou_vang_trang_1l.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rượu vang đỏ
            [
                'product_id' => 5,
                'brand' => 'Red Wine Brand',
                'attribute' => 'CHAI 750ML',
                'description' => 'Rượu vang đỏ, chai 750ml.',
                'price' => 420000,
                'image' => 'ruou_vang_do_750ml.jpg',
                'quantity' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'brand' => 'Red Wine Premium',
                'attribute' => 'CHAI 1L',
                'description' => 'Rượu vang đỏ, chai 1L.',
                'price' => 550000,
                'image' => 'ruou_vang_do_1l.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tã
            [
                'product_id' => 6,
                'brand' => 'Pampers',
                'attribute' => 'BỈM SỐ 3, 50 MIẾNG',
                'description' => 'Tã trẻ em, size 3, 50 miếng.',
                'price' => 180000,
                'image' => 'ta_50.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'brand' => 'Huggies',
                'attribute' => 'BỈM SỐ 4, 60 MIẾNG',
                'description' => 'Tã trẻ em, size 4, 60 miếng.',
                'price' => 220000,
                'image' => 'ta_60.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sữa
            [
                'product_id' => 7,
                'brand' => 'Vinamilk',
                'attribute' => 'SỮA BỘT 400G',
                'description' => 'Sữa bột cho trẻ em, 400g.',
                'price' => 120000,
                'image' => 'sua_bot_400.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'brand' => 'Abbott',
                'attribute' => 'SỮA BỘT 900G',
                'description' => 'Sữa bột cho trẻ em, 900g.',
                'price' => 280000,
                'image' => 'sua_bot_900.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Phụ kiện cho bé
            [
                'product_id' => 8,
                'brand' => 'Fisher-Price',
                'attribute' => 'BỘ ĐỒ CHƠI',
                'description' => 'Bộ phụ kiện đồ chơi cho bé.',
                'price' => 350000,
                'image' => 'phu_kien_do_choi.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'brand' => 'Chicco',
                'attribute' => 'BỘ DỤNG CỤ ĂN DẶM',
                'description' => 'Bộ phụ kiện ăn dặm cho bé.',
                'price' => 420000,
                'image' => 'phu_kien_an_dam.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sữa tắm trẻ em
            [
                'product_id' => 9,
                'brand' => 'Johnson\'s Baby',
                'attribute' => 'CHAI 200ML',
                'description' => 'Sữa tắm trẻ em, 200ml.',
                'price' => 90000,
                'image' => 'sua_tam_JB.jpg',
                'quantity' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'brand' => 'Pigeon',
                'attribute' => 'CHAI 300ML',
                'description' => 'Sữa tắm trẻ em, 300ml.',
                'price' => 120000,
                'image' => 'sua_tam_P.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh mì
            [
                'product_id' => 10,
                'brand' => 'ABC Bakery',
                'attribute' => 'Ổ 400G',
                'description' => 'Bánh mì tươi, 400g.',
                'price' => 25000,
                'image' => 'banh_mi_400g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'brand' => 'XYZ Bakery',
                'attribute' => 'Ổ 500G',
                'description' => 'Bánh mì tươi, 500g.',
                'price' => 30000,
                'image' => 'banh_mi_500g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh bao cuộn
            [
                'product_id' => 11,
                'brand' => 'Happy Bakery',
                'attribute' => 'BỘ 6 CÁI',
                'description' => 'Bánh bao cuộn, 6 cái/bộ.',
                'price' => 40000,
                'image' => 'banh_bao_cuon.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'brand' => 'Tasty Bakery',
                'attribute' => 'BỘ 8 CÁI',
                'description' => 'Bánh bao cuộn, 8 cái/bộ.',
                'price' => 52000,
                'image' => 'banh_bao_cuon_8.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh tortilla
            [
                'product_id' => 12,
                'brand' => 'SoftWrap',
                'attribute' => 'GÓI 10 CÁI',
                'description' => 'Bánh tortilla mềm, 10 cái/gói.',
                'price' => 35000,
                'image' => 'torilla_10.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'brand' => 'WrapMaster',
                'attribute' => 'GÓI 12 CÁI',
                'description' => 'Bánh tortilla mềm, 12 cái/gói.',
                'price' => 42000,
                'image' => 'torilla_12.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh mì sandwich
            [
                'product_id' => 13,
                'brand' => 'Sandwich Co.',
                'attribute' => 'GÓI 6 CÁI',
                'description' => 'Bánh mì sandwich, 6 cái/gói.',
                'price' => 45000,
                'image' => 'sandwich_6.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'brand' => 'BreadHouse',
                'attribute' => 'GÓI 8 CÁI',
                'description' => 'Bánh mì sandwich, 8 cái/gói.',
                'price' => 58000,
                'image' => 'sandwich_8.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Trà
            [
                'product_id' => 14,
                'brand' => 'Lipton',
                'attribute' => 'GÓI 100G',
                'description' => 'Trà túi lọc, 100g.',
                'price' => 80000,
                'image' => 'lipton.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'brand' => 'Dilmah',
                'attribute' => 'GÓI 200G',
                'description' => 'Trà lá rời, 200g.',
                'price' => 150000,
                'image' => 'dilmah.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước khoáng
            [
                'product_id' => 15,
                'brand' => 'Aquafina',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước khoáng tinh khiết, chai 500ml.',
                'price' => 10000,
                'image' => 'aquafina.jpg',
                'quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'brand' => 'LaVie',
                'attribute' => 'CHAI 1L',
                'description' => 'Nước khoáng tinh khiết, chai 1L.',
                'price' => 18000,
                'image' => 'lavie.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Cà phê
            [
                'product_id' => 16,
                'brand' => 'Highland Coffee',
                'attribute' => 'GÓI 250G',
                'description' => 'Cà phê rang xay, 250g.',
                'price' => 120000,
                'image' => 'cf_highland.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'brand' => 'Trung Nguyên',
                'attribute' => 'GÓI 500G',
                'description' => 'Cà phê rang xay, 500g.',
                'price' => 220000,
                'image' => 'trungnguyen.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đồ uống lạnh
            [
                'product_id' => 17,
                'brand' => 'Coca-Cola',
                'attribute' => 'CHAI 330ML',
                'description' => 'Đồ uống lạnh, chai 330ml.',
                'price' => 12000,
                'image' => 'coca.jpg',
                'quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'brand' => 'Pepsi',
                'attribute' => 'CHAI 500ML',
                'description' => 'Đồ uống lạnh, chai 500ml.',
                'price' => 18000,
                'image' => 'pepsi.jpg',
                'quantity' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước ngọt
            [
                'product_id' => 18,
                'brand' => 'Fanta',
                'attribute' => 'CHAI 330ML',
                'description' => 'Nước ngọt có gas, chai 330ml.',
                'price' => 12000,
                'image' => 'fanta.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'brand' => 'Mirinda',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước ngọt có gas, chai 500ml.',
                'price' => 18000,
                'image' => 'mirinda.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước ép trái cây
            [
                'product_id' => 19,
                'brand' => 'Ceres',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước ép trái cây, chai 250ml.',
                'price' => 25000,
                'image' => 'ceres.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'brand' => 'Minute Maid',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước ép trái cây, chai 500ml.',
                'price' => 45000,
                'image' => 'minute_maid.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước tăng lực thể thao
            [
                'product_id' => 20,
                'brand' => 'Red Bull',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước tăng lực, chai 250ml.',
                'price' => 30000,
                'image' => 'redbull.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'brand' => 'Monster',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước tăng lực, chai 500ml.',
                'price' => 50000,
                'image' => 'monster.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hỗn hợp đồ uống ca cao
            [
                'product_id' => 21,
                'brand' => 'Nestlé',
                'attribute' => 'GÓI 200G',
                'description' => 'Hỗn hợp bột ca cao, 200g.',
                'price' => 50000,
                'image' => 'cacao_nestle.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'brand' => 'Ovaltine',
                'attribute' => 'GÓI 400G',
                'description' => 'Hỗn hợp bột ca cao, 400g.',
                'price' => 90000,
                'image' => 'cacao_ovaltine.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ngũ cốc
            [
                'product_id' => 22,
                'brand' => 'Kellogg\'s',
                'attribute' => 'GÓI 250G',
                'description' => 'Ngũ cốc ăn sáng, 250g.',
                'price' => 60000,
                'image' => 'kellogg.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 22,
                'brand' => 'Nestlé',
                'attribute' => 'GÓI 500G',
                'description' => 'Ngũ cốc ăn sáng, 500g.',
                'price' => 110000,
                'image' => 'ngucoc_nestle.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ngũ cốc nóng
            [
                'product_id' => 23,
                'brand' => 'Quaker',
                'attribute' => 'GÓI 300G',
                'description' => 'Ngũ cốc nóng, 300g.',
                'price' => 55000,
                'image' => 'ngucoc_quaker.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 23,
                'brand' => 'Munchy\'s',
                'attribute' => 'GÓI 400G',
                'description' => 'Ngũ cốc nóng, 400g.',
                'price' => 75000,
                'image' => 'ngucoc_muchy.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Granola
            [
                'product_id' => 24,
                'brand' => 'Bob\'s Red Mill',
                'attribute' => 'GÓI 300G',
                'description' => 'Granola hạt, 300g.',
                'price' => 90000,
                'image' => 'granola_300.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 24,
                'brand' => 'Nature Valley',
                'attribute' => 'GÓI 500G',
                'description' => 'Granola hạt, 500g.',
                'price' => 140000,
                'image' => 'granola_500.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Lương khô
            [
                'product_id' => 25,
                'brand' => 'Bakery Co.',
                'attribute' => 'GÓI 200G',
                'description' => 'Lương khô ăn sáng, 200g.',
                'price' => 45000,
                'image' => 'luong_kho_200g.jpg',
                'quantity' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'brand' => 'Healthy Food',
                'attribute' => 'GÓI 300G',
                'description' => 'Lương khô ăn sáng, 300g.',
                'price' => 65000,
                'image' => 'luong_kho_300g.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ngũ cốc (số lượng lớn)
            [
                'product_id' => 26,
                'brand' => 'Kellogg\'s Bulk',
                'attribute' => 'BAO 5KG',
                'description' => 'Ngũ cốc số lượng lớn, bao 5kg.',
                'price' => 550000,
                'image' => 'ngucoc_5kg.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 26,
                'brand' => 'Nestlé Bulk',
                'attribute' => 'BAO 10KG',
                'description' => 'Ngũ cốc số lượng lớn, bao 10kg.',
                'price' => 1000000,
                'image' => 'ngucoc_10kg.jpg',
                'quantity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Trái cây sấy khô (số lượng lớn)
            [
                'product_id' => 27,
                'brand' => 'Dried Fruits Co.',
                'attribute' => 'THÙNG 2KG',
                'description' => 'Trái cây sấy khô, thùng 2kg.',
                'price' => 300000,
                'image' => 'traicay_say_2kg.jpg',
                'quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 27,
                'brand' => 'Tropical Dried',
                'attribute' => 'THÙNG 5KG',
                'description' => 'Trái cây sấy khô, thùng 5kg.',
                'price' => 700000,
                'image' => 'traicay_say_5kg.jpg',
                'quantity' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đậu đóng hộp
            [
                'product_id' => 28,
                'brand' => 'Heinz',
                'attribute' => 'HỘP 400G',
                'description' => 'Đậu đóng hộp, hộp 400g.',
                'price' => 35000,
                'image' => 'dau_400g.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 28,
                'brand' => 'Bonduelle',
                'attribute' => 'HỘP 500G',
                'description' => 'Đậu đóng hộp, hộp 500g.',
                'price' => 45000,
                'image' => 'dau_500g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sốt táo đóng hộp
            [
                'product_id' => 29,
                'brand' => 'Mott\'s',
                'attribute' => 'HỘP 400G',
                'description' => 'Sốt táo đóng hộp, hộp 400g.',
                'price' => 40000,
                'image' => 'sot_tao_400g.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 29,
                'brand' => 'Del Monte',
                'attribute' => 'HỘP 500G',
                'description' => 'Sốt táo đóng hộp, hộp 500g.',
                'price' => 50000,
                'image' => 'sot_tao_500g.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rau củ đóng hộp
            [
                'product_id' => 30,
                'brand' => 'Green Giant',
                'attribute' => 'HỘP 400G',
                'description' => 'Rau củ đóng hộp, hộp 400g.',
                'price' => 35000,
                'image' => 'rau_cu_dong_400g.jpg',
                'quantity' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 30,
                'brand' => 'Lean Cuisine',
                'attribute' => 'HỘP 500G',
                'description' => 'Rau củ đóng hộp, hộp 500g.',
                'price' => 45000,
                'image' => 'rau_cu_dong_500g.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước dùng súp đóng hộp
            [
                'product_id' => 31,
                'brand' => 'Knorr',
                'attribute' => 'HỘP 500ML',
                'description' => 'Nước dùng súp đóng hộp, 500ml.',
                'price' => 55000,
                'image' => 'nuoc_sup_500ml.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 31,
                'brand' => 'Maggi',
                'attribute' => 'HỘP 1L',
                'description' => 'Nước dùng súp đóng hộp, 1L.',
                'price' => 95000,
                'image' => 'nuoc_sup_1l.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thịt hộp
            [
                'product_id' => 32,
                'brand' => 'Lean Cuisine',
                'attribute' => 'HỘP 200G',
                'description' => 'Thịt hộp, hộp 200g.',
                'price' => 60000,
                'image' => 'thit_hop_200.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 32,
                'brand' => 'Cattle King',
                'attribute' => 'HỘP 300G',
                'description' => 'Thịt hộp, hộp 300g.',
                'price' => 85000,
                'image' => 'thit_hop_300.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đậu nành không lactose
            [
                'product_id' => 33,
                'brand' => 'Alpro',
                'attribute' => 'CHAI 1L',
                'description' => 'Sữa đậu nành không lactose, 1L.',
                'price' => 65000,
                'image' => 'sua_dau_nanh_1l.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 33,
                'brand' => 'Silk',
                'attribute' => 'CHAI 500ML',
                'description' => 'Sữa đậu nành không lactose, 500ml.',
                'price' => 35000,
                'image' => 'sua_dau_nanh_500ml.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bơ
            [
                'product_id' => 34,
                'brand' => 'Anchor',
                'attribute' => 'CỌC 200G',
                'description' => 'Bơ tươi, 200g.',
                'price' => 70000,
                'image' => 'bo_200g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 34,
                'brand' => 'Lurpak',
                'attribute' => 'CỌC 250G',
                'description' => 'Bơ tươi, 250g.',
                'price' => 85000,
                'image' => 'bo_250g.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sữa chua
            [
                'product_id' => 35,
                'brand' => 'Vinamilk',
                'attribute' => 'HỘP 100G',
                'description' => 'Sữa chua, 100g.',
                'price' => 15000,
                'image' => 'suachua_100g.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 35,
                'brand' => 'TH True Yogurt',
                'attribute' => 'HỘP 150G',
                'description' => 'Sữa chua, 150g.',
                'price' => 20000,
                'image' => 'suachua_150g.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sữa tươi
            [
                'product_id' => 36,
                'brand' => 'Vinamilk',
                'attribute' => 'CHAI 1L',
                'description' => 'Sữa tươi tiệt trùng, 1L.',
                'price' => 45000,
                'image' => 'suatuoi_1l.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 36,
                'brand' => 'TH True Milk',
                'attribute' => 'CHAI 500ML',
                'description' => 'Sữa tươi tiệt trùng, 500ml.',
                'price' => 25000,
                'image' => 'suatuoi_500ml.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Phô mai đóng gói
            [
                'product_id' => 37,
                'brand' => 'Kraft',
                'attribute' => 'GÓI 200G',
                'description' => 'Phô mai lát đóng gói, 200g.',
                'price' => 80000,
                'image' => 'phomai_lat_200g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 37,
                'brand' => 'President',
                'attribute' => 'GÓI 250G',
                'description' => 'Phô mai lát đóng gói, 250g.',
                'price' => 95000,
                'image' => 'phomai_lat_250g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Trứng
            [
                'product_id' => 38,
                'brand' => 'VietEgg',
                'attribute' => 'HỘP 10 TRỨNG',
                'description' => 'Trứng gà tươi, hộp 10 quả.',
                'price' => 40000,
                'image' => 'trung_ga_10.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 38,
                'brand' => 'Happy Egg',
                'attribute' => 'HỘP 12 TRỨNG',
                'description' => 'Trứng gà tươi, hộp 12 quả.',
                'price' => 48000,
                'image' => 'trung_ga_12.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kem tươi
            [
                'product_id' => 39,
                'brand' => 'Anchor',
                'attribute' => 'CHAI 250ML',
                'description' => 'Kem tươi, 250ml.',
                'price' => 65000,
                'image' => 'kem_tuoi_250ml.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 39,
                'brand' => 'Devon',
                'attribute' => 'CHAI 500ML',
                'description' => 'Kem tươi, 500ml.',
                'price' => 120000,
                'image' => 'kem_tuoi_500ml.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kem sữa
            [
                'product_id' => 40,
                'brand' => 'Nestlé',
                'attribute' => 'CHAI 250ML',
                'description' => 'Kem sữa tươi, 250ml.',
                'price' => 60000,
                'image' => 'kem_sua_250ml.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 40,
                'brand' => 'Devon',
                'attribute' => 'CHAI 500ML',
                'description' => 'Kem sữa tươi, 500ml.',
                'price' => 110000,
                'image' => 'kem_sua_500ml.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh pudding
            [
                'product_id' => 41,
                'brand' => 'Muller',
                'attribute' => 'HỘP 150G',
                'description' => 'Bánh pudding, hộp 150g.',
                'price' => 35000,
                'image' => 'pudding_150g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 41,
                'brand' => 'Danone',
                'attribute' => 'HỘP 200G',
                'description' => 'Bánh pudding, hộp 200g.',
                'price' => 45000,
                'image' => 'pudding_200g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Phô mai đặc biệt
            [
                'product_id' => 42,
                'brand' => 'Brie Co.',
                'attribute' => 'GÓI 200G',
                'description' => 'Phô mai đặc biệt, 200g.',
                'price' => 120000,
                'image' => 'phomai_200g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 42,
                'brand' => 'Camembert',
                'attribute' => 'GÓI 250G',
                'description' => 'Phô mai đặc biệt, 250g.',
                'price' => 150000,
                'image' => 'phomai_250g.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thịt nguội
            [
                'product_id' => 43,
                'brand' => 'Baroni',
                'attribute' => 'GÓI 200G',
                'description' => 'Thịt nguội, gói 200g.',
                'price' => 95000,
                'image' => 'thit_nguoi_200g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 43,
                'brand' => 'Herta',
                'attribute' => 'GÓI 250G',
                'description' => 'Thịt nguội, gói 250g.',
                'price' => 115000,
                'image' => 'thit_nguoi_250g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước chấm
            [
                'product_id' => 44,
                'brand' => 'Heinz',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước chấm, chai 250ml.',
                'price' => 35000,
                'image' => 'nuoc_cham_250ml.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 44,
                'brand' => 'Lee Kum Kee',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước chấm, chai 500ml.',
                'price' => 60000,
                'image' => 'nuoc_cham_500ml.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước sốt chế biến Salad
            [
                'product_id' => 45,
                'brand' => 'Kraft',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước sốt chế biến Salad, 250ml.',
                'price' => 40000,
                'image' => 'nuoc_salad_250ml.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 45,
                'brand' => 'Hellmann\'s',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước sốt chế biến Salad, 500ml.',
                'price' => 70000,
                'image' => 'nuoc_salad_500ml.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bữa ăn chế biến sẵn
            [
                'product_id' => 46,
                'brand' => 'Lean Cuisine',
                'attribute' => 'HỘP 300G',
                'description' => 'Bữa ăn chế biến sẵn, hộp 300g.',
                'price' => 120000,
                'image' => 'bua_an_300g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 46,
                'brand' => 'Lean Cuisine',
                'attribute' => 'HỘP 400G',
                'description' => 'Bữa ăn chế biến sẵn, hộp 400g.',
                'price' => 150000,
                'image' => 'bua_an_400g.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đậu hũ
            [
                'product_id' => 47,
                'brand' => 'Tofun',
                'attribute' => 'KHAY 300G',
                'description' => 'Đậu hũ tươi, khay 300g.',
                'price' => 35000,
                'image' => 'dau_hu_300g.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 47,
                'brand' => 'Vegan Delight',
                'attribute' => 'KHAY 500G',
                'description' => 'Đậu hũ tươi, khay 500g.',
                'price' => 55000,
                'image' => 'dau_hu_500g.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mì tươi
            [
                'product_id' => 48,
                'brand' => 'Hảo Hảo',
                'attribute' => 'TÚI 300G',
                'description' => 'Mì tươi, túi 300g, 20 vắt.',
                'price' => 20000,
                'image' => 'mi_goi_300g.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 48,
                'brand' => 'Acecook',
                'attribute' => 'GÓI 500G',
                'description' => 'Mì tươi, gói 500g, 30 vắt.',
                'price' => 30000,
                'image' => 'mi_goi_500g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước sốt mì
            [
                'product_id' => 49,
                'brand' => 'Knorr',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước sốt mì, chai 250ml.',
                'price' => 35000,
                'image' => 'nuoc_sot_mi_250ml.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 49,
                'brand' => 'Panzani',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước sốt mì, chai 500ml.',
                'price' => 65000,
                'image' => 'nuoc_sot_mi_500ml.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mì khô
            [
                'product_id' => 50,
                'brand' => 'Vifon',
                'attribute' => 'GÓI 400G',
                'description' => 'Mì khô, gói 400g.',
                'price' => 25000,
                'image' => 'mi_kho_400g.jpg',
                'quantity' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 50,
                'brand' => 'Acecook',
                'attribute' => 'GÓI 500G',
                'description' => 'Mì khô, gói 500g.',
                'price' => 30000,
                'image' => 'mi_kho_500g.jpg',
                'quantity' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mì ngũ cốc
            [
                'product_id' => 51,
                'brand' => 'Nature\'s Own',
                'attribute' => 'GÓI 300G',
                'description' => 'Mì ngũ cốc, gói 300g.',
                'price' => 40000,
                'image' => 'my_ngu_coc_300g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 51,
                'brand' => 'Barilla',
                'attribute' => 'GÓI 500G',
                'description' => 'Mì ngũ cốc, gói 500g.',
                'price' => 65000,
                'image' => 'my_ngu_coc_500g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mì ăn liền
            [
                'product_id' => 52,
                'brand' => 'Hảo Hảo',
                'attribute' => 'GÓI 75G',
                'description' => 'Mì ăn liền, gói 75g.',
                'price' => 6000,
                'image' => 'haohao.jpg',
                'quantity' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 52,
                'brand' => 'Omachi',
                'attribute' => 'GÓI 80G',
                'description' => 'Mì ăn liền, gói 80g.',
                'price' => 7000,
                'image' => 'omachi.jpg',
                'quantity' => 280,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đĩa sứ
            [
                'product_id' => 53,
                'brand' => 'Corelle',
                'attribute' => 'BỘ 6 CÁI',
                'description' => 'Đĩa sứ, bộ 6 cái.',
                'price' => 450000,
                'image' => 'dia_su_6.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 53,
                'brand' => 'Luminarc',
                'attribute' => 'BỘ 4 CÁI',
                'description' => 'Đĩa sứ, bộ 4 cái.',
                'price' => 350000,
                'image' => 'dia_su_4.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đĩa giấy
            [
                'product_id' => 54,
                'brand' => 'Duni',
                'attribute' => 'GÓI 50 CÁI',
                'description' => 'Đĩa giấy, gói 50 cái.',
                'price' => 60000,
                'image' => 'dia_giay_50.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 54,
                'brand' => 'Fine Life',
                'attribute' => 'GÓI 100 CÁI',
                'description' => 'Đĩa giấy, gói 100 cái.',
                'price' => 110000,
                'image' => 'dia_giay_100.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Màng bọc thực phẩm
            [
                'product_id' => 55,
                'brand' => 'Glad',
                'attribute' => 'CUỘN 30M',
                'description' => 'Màng bọc thực phẩm, cuộn 30m.',
                'price' => 45000,
                'image' => 'mang_boctp_30m.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 55,
                'brand' => 'WrapMaster',
                'attribute' => 'CUỘN 50M',
                'description' => 'Màng bọc thực phẩm, cuộn 50m.',
                'price' => 80000,
                'image' => 'mang_boctp_50m.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bột giặt
            [
                'product_id' => 56,
                'brand' => 'Omo',
                'attribute' => 'BAO 2KG',
                'description' => 'Bột giặt, bao 2kg.',
                'price' => 120000,
                'image' => 'omo.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 56,
                'brand' => 'Tide',
                'attribute' => 'BAO 3KG',
                'description' => 'Bột giặt, bao 3kg.',
                'price' => 170000,
                'image' => 'tide.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước hoa xịt phòng
            [
                'product_id' => 57,
                'brand' => 'Glade',
                'attribute' => 'CHAI 300ML',
                'description' => 'Nước hoa xịt phòng, 300ml.',
                'price' => 85000,
                'image' => 'nuoc_hoa_glade.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 57,
                'brand' => 'Air Wick',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước hoa xịt phòng, 500ml.',
                'price' => 120000,
                'image' => 'nuoc_hoa_airwick.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước tẩy bồn cầu
            [
                'product_id' => 58,
                'brand' => 'Duck',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước tẩy bồn cầu, 500ml.',
                'price' => 60000,
                'image' => 'duck.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 58,
                'brand' => 'Harpic',
                'attribute' => 'CHAI 750ML',
                'description' => 'Nước tẩy bồn cầu, 750ml.',
                'price' => 85000,
                'image' => 'Harpic.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Túi rác
            [
                'product_id' => 59,
                'brand' => 'Hefty',
                'attribute' => 'CUỘN 20 CÁI',
                'description' => 'Túi rác, cuộn 20 cái.',
                'price' => 40000,
                'image' => 'tui_rac_20.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 59,
                'brand' => 'Vina Bag',
                'attribute' => 'CUỘN 30 CÁI',
                'description' => 'Túi rác, cuộn 30 cái.',
                'price' => 55000,
                'image' => 'tui_rac_30.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước rửa chén
            [
                'product_id' => 60,
                'brand' => 'Sunlight',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước rửa chén, 500ml.',
                'price' => 40000,
                'image' => 'rua_chen_500ml.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 60,
                'brand' => 'Dawn',
                'attribute' => 'CHAI 750ML',
                'description' => 'Nước rửa chén, 750ml.',
                'price' => 65000,
                'image' => 'rua_chen_750ml.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Dao
            [
                'product_id' => 61,
                'brand' => 'Victorinox',
                'attribute' => 'DAO BẾP 20CM',
                'description' => 'Dao bếp, lưỡi 20cm.',
                'price' => 250000,
                'image' => 'dao_20cm.jpg',
                'quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 61,
                'brand' => 'Zwilling',
                'attribute' => 'DAO BẾP 25CM',
                'description' => 'Dao bếp, lưỡi 25cm.',
                'price' => 350000,
                'image' => 'dao_30cm.jpg',
                'quantity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chảo
            [
                'product_id' => 62,
                'brand' => 'Tefal',
                'attribute' => 'CHẢO 24CM',
                'description' => 'Chảo chống dính, 24cm.',
                'price' => 450000,
                'image' => 'chao_24cm.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 62,
                'brand' => 'Lock&Lock',
                'attribute' => 'CHẢO 28CM',
                'description' => 'Chảo chống dính, 28cm.',
                'price' => 550000,
                'image' => 'chao_28cm.jpg',
                'quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thịt gà tươi
            [
                'product_id' => 63,
                'brand' => 'Gà Đông Á',
                'attribute' => '1 kg',
                'description' => 'Thịt gà tươi, 1kg.',
                'price' => 120000,
                'image' => 'ga_1kg.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 63,
                'brand' => 'Gà Á Châu',
                'attribute' => '1.5 kg',
                'description' => 'Thịt gà tươi, 1.5kg.',
                'price' => 175000,
                'image' => 'ga_1.5kg.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thịt gà đóng gói
            [
                'product_id' => 64,
                'brand' => 'Vissan',
                'attribute' => 'GÓI 500G',
                'description' => 'Thịt gà đóng gói, 500g.',
                'price' => 85000,
                'image' => 'ga_500g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 64,
                'brand' => 'CP',
                'attribute' => 'GÓI 1KG',
                'description' => 'Thịt gà đóng gói, 1kg.',
                'price' => 160000,
                'image' => 'ga_donggoi.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Xúc xích xông khói
            [
                'product_id' => 65,
                'brand' => 'Vissan',
                'attribute' => 'GÓI 300G',
                'description' => 'Xúc xích xông khói, gói 300g.',
                'price' => 75000,
                'image' => 'xuc_xich_300g.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 65,
                'brand' => 'CP',
                'attribute' => 'GÓI 500G',
                'description' => 'Xúc xích xông khói, gói 500g.',
                'price' => 120000,
                'image' => 'xuc_xich_500g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thịt heo tươi
            [
                'product_id' => 66,
                'brand' => 'Heo VietGAP',
                'attribute' => 'KG 1',
                'description' => 'Thịt heo tươi, 1kg.',
                'price' => 140000,
                'image' => 'heo_tuoi_1kg.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 66,
                'brand' => 'Heo CP',
                'attribute' => 'KG 1.5',
                'description' => 'Thịt heo tươi, 1.5kg.',
                'price' => 200000,
                'image' => 'heo_tuoi_1.5kg.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Cá ngừ đóng gói
            [
                'product_id' => 67,
                'brand' => 'John West',
                'attribute' => 'HỘP 150G',
                'description' => 'Cá ngừ đóng gói, hộp 150g.',
                'price' => 65000,
                'image' => 'ca_ngu150.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 67,
                'brand' => 'Crown Prince',
                'attribute' => 'HỘP 200G',
                'description' => 'Cá ngừ đóng gói, hộp 200g.',
                'price' => 85000,
                'image' => 'ca_ngu200.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thịt đóng gói
            [
                'product_id' => 68,
                'brand' => 'Vissan',
                'attribute' => 'GÓI 500G',
                'description' => 'Thịt đóng gói, 500g.',
                'price' => 90000,
                'image' => 'thit_dong_goi_500g.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 68,
                'brand' => 'CP',
                'attribute' => 'GÓI 1KG',
                'description' => 'Thịt đóng gói, 1kg.',
                'price' => 170000,
                'image' => 'thit_dong_goi_1kg.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Quầy hải sản
            [
                'product_id' => 69,
                'brand' => 'Hải Sản Biển Đông',
                'attribute' => 'KG 1',
                'description' => 'Hải sản tươi sống, 1kg.',
                'price' => 220000,
                'image' => 'hai_san_1kg.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 69,
                'brand' => 'Hải Sản Cà Mau',
                'attribute' => 'KG 1.5',
                'description' => 'Hải sản tươi sống, 1.5kg.',
                'price' => 330000,
                'image' => 'hai_san_1.5kg.jpg',
                'quantity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bột làm bánh
            [
                'product_id' => 70,
                'brand' => 'Aunt Jemima',
                'attribute' => 'BAO 500G',
                'description' => 'Bột làm bánh, bao 500g.',
                'price' => 55000,
                'image' => 'bot_banhbao_500g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 70,
                'brand' => 'King Arthur',
                'attribute' => 'BAO 1KG',
                'description' => 'Bột làm bánh, bao 1kg.',
                'price' => 95000,
                'image' => 'bot_banhbao_1kg.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đồ ngâm chua ô liu
            [
                'product_id' => 71,
                'brand' => 'Filippo Berio',
                'attribute' => 'HŨ 200G',
                'description' => 'Đồ ngâm chua ô liu, hũ 200g.',
                'price' => 65000,
                'image' => 'oliu_200g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 71,
                'brand' => 'Borges',
                'attribute' => 'HŨ 350G',
                'description' => 'Đồ ngâm chua ô liu, hũ 350g.',
                'price' => 95000,
                'image' => 'oliu_350g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Siro mật ong
            [
                'product_id' => 72,
                'brand' => 'Nature\'s Nectar',
                'attribute' => 'CHAI 250ML',
                'description' => 'Siro mật ong, chai 250ml.',
                'price' => 85000,
                'image' => 'siro_matong_250ml.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 72,
                'brand' => 'Honeywell',
                'attribute' => 'CHAI 500ML',
                'description' => 'Siro mật ong, chai 500ml.',
                'price' => 150000,
                'image' => 'siro_matong_500ml.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Muối
            [
                'product_id' => 73,
                'brand' => 'Morton',
                'attribute' => 'HỘP 500G',
                'description' => 'Muối ăn, hộp 500g.',
                'price' => 15000,
                'image' => 'muoi_500g.jpg',
                'quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 73,
                'brand' => 'Ajinomoto',
                'attribute' => 'HỘP 1KG',
                'description' => 'Muối ăn, hộp 1kg.',
                'price' => 25000,
                'image' => 'muoi_1kg.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bơ phết bánh mì
            [
                'product_id' => 74,
                'brand' => 'President',
                'attribute' => 'HŨ 200G',
                'description' => 'Bơ phết bánh mì, hũ 200g.',
                'price' => 45000,
                'image' => 'bo_banhmi_200g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 74,
                'brand' => 'Anchor',
                'attribute' => 'HŨ 400G',
                'description' => 'Bơ phết bánh mì, hũ 400g.',
                'price' => 85000,
                'image' => 'bo_banhmi_400g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đường
            [
                'product_id' => 75,
                'brand' => 'Cát Thủ Dầu Một',
                'attribute' => 'BAO 1KG',
                'description' => 'Đường trắng, bao 1kg.',
                'price' => 20000,
                'image' => 'duong_1kg.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 75,
                'brand' => 'Phú Mỹ',
                'attribute' => 'BAO 2KG',
                'description' => 'Đường trắng, bao 2kg.',
                'price' => 35000,
                'image' => 'duong_2kg.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bơ phết
            [
                'product_id' => 76,
                'brand' => 'Lurpak',
                'attribute' => 'HŨ 250G',
                'description' => 'Bơ phết, hũ 250g.',
                'price' => 65000,
                'image' => 'bophet_250g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 76,
                'brand' => 'Elle & Vire',
                'attribute' => 'HŨ 500G',
                'description' => 'Bơ phết, hũ 500g.',
                'price' => 120000,
                'image' => 'bophet_500g.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước sốt salad
            [
                'product_id' => 77,
                'brand' => 'Kraft',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước sốt salad, chai 250ml.',
                'price' => 40000,
                'image' => 'sotsalad_250ml.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 77,
                'brand' => 'Hellmann\'s',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước sốt salad, chai 500ml.',
                'price' => 75000,
                'image' => 'sotsalad_500ml.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Gelatin
            [
                'product_id' => 78,
                'brand' => 'Knox',
                'attribute' => 'GÓI 85G',
                'description' => 'Gelatin làm bánh, gói 85g.',
                'price' => 35000,
                'image' => 'gelatin_85g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 78,
                'brand' => 'Dr. Oetker',
                'attribute' => 'GÓI 100G',
                'description' => 'Gelatin làm bánh, gói 100g.',
                'price' => 40000,
                'image' => 'gelatin_100g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Giấm
            [
                'product_id' => 79,
                'brand' => 'Heinz',
                'attribute' => 'CHAI 500ML',
                'description' => 'Giấm ăn, chai 500ml.',
                'price' => 35000,
                'image' => 'dam_500ml.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 79,
                'brand' => 'Pomace',
                'attribute' => 'CHAI 1L',
                'description' => 'Giấm ăn, chai 1L.',
                'price' => 60000,
                'image' => 'dam_1l.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nước ướp thịt
            [
                'product_id' => 80,
                'brand' => 'Knorr',
                'attribute' => 'CHAI 250ML',
                'description' => 'Nước ướp thịt, chai 250ml.',
                'price' => 40000,
                'image' => 'nuoc_uop_thit_250ml.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 80,
                'brand' => 'Maggi',
                'attribute' => 'CHAI 500ML',
                'description' => 'Nước ướp thịt, chai 500ml.',
                'price' => 75000,
                'image' => 'nuoc_uop_thit_500ml.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đồ trang trí bánh ngọt
            [
                'product_id' => 81,
                'brand' => 'Wilton',
                'attribute' => 'HŨ 100G',
                'description' => 'Đồ trang trí bánh ngọt, hũ 100g.',
                'price' => 45000,
                'image' => 'trangtri_banh_100g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 81,
                'brand' => 'FunCakes',
                'attribute' => 'HŨ 200G',
                'description' => 'Đồ trang trí bánh ngọt, hũ 200g.',
                'price' => 80000,
                'image' => 'trangtri_banh_200g.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kem đánh răng
            [
                'product_id' => 82,
                'brand' => 'Colgate',
                'attribute' => 'TUÝP 100G',
                'description' => 'Kem đánh răng Colgate, 100g.',
                'price' => 25000,
                'image' => 'colgate.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 82,
                'brand' => 'P/S',
                'attribute' => 'TUÝP 120G',
                'description' => 'Kem đánh răng P/S, 120g.',
                'price' => 28000,
                'image' => 'PS.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Xà phòng
            [
                'product_id' => 83,
                'brand' => 'Lifebuoy',
                'attribute' => 'THẺ 100G',
                'description' => 'Xà phòng Lifebuoy, 100g.',
                'price' => 15000,
                'image' => 'lifeboy.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 83,
                'brand' => 'Dove',
                'attribute' => 'THẺ 120G',
                'description' => 'Xà phòng Dove, 120g.',
                'price' => 22000,
                'image' => 'dove.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Miếng dán giảm đau
            [
                'product_id' => 84,
                'brand' => 'Salonpas',
                'attribute' => 'HỘP 10 MIẾNG',
                'description' => 'Miếng dán giảm đau Salonpas, hộp 10 miếng.',
                'price' => 45000,
                'image' => 'salonpas.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 84,
                'brand' => 'Tiger Balm',
                'attribute' => 'HỘP 5 MIẾNG',
                'description' => 'Miếng dán giảm đau Tiger Balm, hộp 5 miếng.',
                'price' => 40000,
                'image' => 'tigerbalm.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thuốc cảm cúm
            [
                'product_id' => 85,
                'brand' => 'Panadol Cold',
                'attribute' => 'HỘP 10 VIÊN',
                'description' => 'Thuốc cảm cúm Panadol Cold, hộp 10 viên.',
                'price' => 30000,
                'image' => 'panadol.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 85,
                'brand' => 'Decolgen',
                'attribute' => 'HỘP 12 VIÊN',
                'description' => 'Thuốc cảm cúm Decolgen, hộp 12 viên.',
                'price' => 35000,
                'image' => 'decolgen.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Băng vệ sinh
            [
                'product_id' => 86,
                'brand' => 'Kotex',
                'attribute' => 'HỘP 10 CÁI',
                'description' => 'Băng vệ sinh Kotex, hộp 10 cái.',
                'price' => 25000,
                'image' => 'kotex.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 86,
                'brand' => 'Laurier',
                'attribute' => 'HỘP 12 CÁI',
                'description' => 'Băng vệ sinh Laurier, hộp 12 cái.',
                'price' => 30000,
                'image' => 'Laurier.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thuốc nhỏ mắt
            [
                'product_id' => 87,
                'brand' => 'Rohto',
                'attribute' => 'CHAI 10ML',
                'description' => 'Thuốc nhỏ mắt Rohto, chai 10ml.',
                'price' => 55000,
                'image' => 'Rohto.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 87,
                'brand' => 'Visine',
                'attribute' => 'CHAI 15ML',
                'description' => 'Thuốc nhỏ mắt Visine, chai 15ml.',
                'price' => 65000,
                'image' => 'Visine.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Dao cạo râu
            [
                'product_id' => 88,
                'brand' => 'Gillette',
                'attribute' => 'HỘP 3 LƯỠI',
                'description' => 'Dao cạo râu Gillette, hộp 3 lưỡi.',
                'price' => 120000,
                'image' => 'dao_cao_Gil.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 88,
                'brand' => 'Bic',
                'attribute' => 'HỘP 5 LƯỠI',
                'description' => 'Dao cạo râu Bic, hộp 5 lưỡi.',
                'price' => 95000,
                'image' => 'dao_cao_Bic.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kem dưỡng da
            [
                'product_id' => 89,
                'brand' => 'Nivea',
                'attribute' => 'TUÝP 50ML',
                'description' => 'Kem dưỡng da Nivea, tuýp 50ml.',
                'price' => 65000,
                'image' => 'Nivea.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 89,
                'brand' => 'Olay',
                'attribute' => 'TUÝP 100ML',
                'description' => 'Kem dưỡng da Olay, tuýp 100ml.',
                'price' => 120000,
                'image' => 'Olay.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Lăn khử mùi
            [
                'product_id' => 90,
                'brand' => 'Rexona',
                'attribute' => 'CHAI 50ML',
                'description' => 'Lăn khử mùi Rexona, 50ml.',
                'price' => 45000,
                'image' => 'rexona.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 90,
                'brand' => 'Nivea',
                'attribute' => 'CHAI 75ML',
                'description' => 'Lăn khử mùi Nivea, 75ml.',
                'price' => 65000,
                'image' => 'lan_nivea.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Protein thay thế bữa ăn
            [
                'product_id' => 91,
                'brand' => 'Ensure',
                'attribute' => 'HỘP 400G',
                'description' => 'Protein thay thế bữa ăn Ensure, hộp 400g.',
                'price' => 150000,
                'image' => 'Ensure.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 91,
                'brand' => 'Optimum Nutrition',
                'attribute' => 'HỘP 500G',
                'description' => 'Protein thay thế bữa ăn Optimum Nutrition, hộp 500g.',
                'price' => 220000,
                'image' => 'optinum_nutrition.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Men tiêu hóa
            [
                'product_id' => 92,
                'brand' => 'Yakult',
                'attribute' => 'CHAI 65ML',
                'description' => 'Men tiêu hóa Yakult, chai 65ml.',
                'price' => 15000,
                'image' => 'yakult.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 92,
                'brand' => 'Probiotic',
                'attribute' => 'CHAI 100ML',
                'description' => 'Men tiêu hóa Probiotic, chai 100ml.',
                'price' => 25000,
                'image' => 'probiotic.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sữa dưỡng thể
            [
                'product_id' => 93,
                'brand' => 'Nivea',
                'attribute' => 'CHAI 200ML',
                'description' => 'Sữa dưỡng thể Nivea, 200ml.',
                'price' => 85000,
                'image' => 'sua_duongthe_nivea.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 93,
                'brand' => 'Vaseline',
                'attribute' => 'CHAI 250ML',
                'description' => 'Sữa dưỡng thể Vaseline, 250ml.',
                'price' => 95000,
                'image' => 'sua_duongthe_vaseline.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Dầu gội
            [
                'product_id' => 94,
                'brand' => 'Clear',
                'attribute' => 'CHAI 200ML',
                'description' => 'Dầu gội Clear, 200ml.',
                'price' => 75000,
                'image' => 'clear.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 94,
                'brand' => 'Pantene',
                'attribute' => 'CHAI 250ML',
                'description' => 'Dầu gội Pantene, 250ml.',
                'price' => 95000,
                'image' => 'pantene.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vitamin
            [
                'product_id' => 95,
                'brand' => 'Centrum',
                'attribute' => 'HỘP 30 VIÊN',
                'description' => 'Vitamin tổng hợp Centrum, hộp 30 viên.',
                'price' => 120000,
                'image' => 'vitamin_centrum.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 95,
                'brand' => 'Nature Made',
                'attribute' => 'HỘP 60 VIÊN',
                'description' => 'Vitamin Nature Made, hộp 60 viên.',
                'price' => 200000,
                'image' => 'vitamin_nature.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hộp sơ cứu
            [
                'product_id' => 96,
                'brand' => 'First Aid',
                'attribute' => 'HỘP 1',
                'description' => 'Hộp sơ cứu cơ bản, 1 hộp.',
                'price' => 150000,
                'image' => 'hop_so_cuu_coban.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 96,
                'brand' => 'Johnson & Johnson',
                'attribute' => 'HỘP 1',
                'description' => 'Hộp sơ cứu J&J, 1 hộp.',
                'price' => 180000,
                'image' => 'hop_so_cuu_JJ.jpg',
                'quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mặt nạ dưỡng da
            [
                'product_id' => 97,
                'brand' => 'Innisfree',
                'attribute' => 'MIẾNG 1',
                'description' => 'Mặt nạ dưỡng da Innisfree, 1 miếng.',
                'price' => 25000,
                'image' => 'ma_na_innisfree.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 97,
                'brand' => 'Mediheal',
                'attribute' => 'MIẾNG 1',
                'description' => 'Mặt nạ dưỡng da Mediheal, 1 miếng.',
                'price' => 30000,
                'image' => 'ma_na_mediheal.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kem dưỡng da (variant khác)
            [
                'product_id' => 98,
                'brand' => 'The Face Shop',
                'attribute' => 'TUÝP 50ML',
                'description' => 'Kem dưỡng da The Face Shop, tuýp 50ml.',
                'price' => 70000,
                'image' => 'kem_duong_theface.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 98,
                'brand' => 'Hada Labo',
                'attribute' => 'TUÝP 50ML',
                'description' => 'Kem dưỡng da Hada Labo, tuýp 50ml.',
                'price' => 85000,
                'image' => 'kem_duong_hada.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thức ăn cho chó
            [
                'product_id' => 99,
                'brand' => 'Pedigree',
                'attribute' => 'BAO 2KG',
                'description' => 'Thức ăn cho chó Pedigree, bao 2kg.',
                'price' => 150000,
                'image' => 'dog_food_pedigree.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 99,
                'brand' => 'Royal Canin',
                'attribute' => 'BAO 3KG',
                'description' => 'Thức ăn cho chó Royal Canin, bao 3kg.',
                'price' => 250000,
                'image' => 'dog_food_royalcanin.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thức ăn cho mèo
            [
                'product_id' => 100,
                'brand' => 'Whiskas',
                'attribute' => 'BAO 1.5KG',
                'description' => 'Thức ăn cho mèo Whiskas, bao 1.5kg.',
                'price' => 120000,
                'image' => 'cat_food_whiskas.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 100,
                'brand' => 'Royal Canin',
                'attribute' => 'BAO 2KG',
                'description' => 'Thức ăn cho mèo Royal Canin, bao 2kg.',
                'price' => 200000,
                'image' => 'cat_food_royal.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bắp cải
            [
                'product_id' => 101,
                'brand' => 'Fresh Farm',
                'attribute' => 'CÁI 1KG',
                'description' => 'Bắp cải tươi, 1kg.',
                'price' => 30000,
                'image' => 'bap_cai_1kg.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 101,
                'brand' => 'Green Valley',
                'attribute' => 'CÁI 1.5KG',
                'description' => 'Bắp cải tươi, 1.5kg.',
                'price' => 45000,
                'image' => 'bap_cai_1.5kg.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Táo
            [
                'product_id' => 102,
                'brand' => 'Envy',
                'attribute' => 'TRÁI 1KG',
                'description' => 'Táo Envy tươi, 1kg.',
                'price' => 60000,
                'image' => 'tao_envy_1kg.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 102,
                'brand' => 'Fuji',
                'attribute' => 'TRÁI 1.5KG',
                'description' => 'Táo Fuji tươi, 1.5kg.',
                'price' => 85000,
                'image' => 'tao_fuji_1.5kg.jpg',
                'quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bắp cải đóng gói
            [
                'product_id' => 103,
                'brand' => 'Fresh Farm',
                'attribute' => 'BAO 500G',
                'description' => 'Bắp cải đã rửa và đóng gói, 500g.',
                'price' => 35000,
                'image' => 'bap_cai_donggoi_500g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 103,
                'brand' => 'Green Valley',
                'attribute' => 'BAO 1KG',
                'description' => 'Bắp cải đóng gói, 1kg.',
                'price' => 60000,
                'image' => 'bap_cai_donggoi_1kg.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Táo đóng hộp
            [
                'product_id' => 104,
                'brand' => 'Del Monte',
                'attribute' => 'HỘP 400G',
                'description' => 'Táo đóng hộp Del Monte, 400g.',
                'price' => 40000,
                'image' => 'tao_dong_hop_400g.jpg',
                'quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 104,
                'brand' => 'Dole',
                'attribute' => 'HỘP 500G',
                'description' => 'Táo đóng hộp Dole, 500g.',
                'price' => 50000,
                'image' => 'tao_dong_hop_500g.jpg',
                'quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rau thơm
            [
                'product_id' => 105,
                'brand' => 'Green Farm',
                'attribute' => 'BÓ 50G',
                'description' => 'Rau thơm tươi, bó 50g.',
                'price' => 15000,
                'image' => 'rau_bo_50g.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 105,
                'brand' => 'Herb Garden',
                'attribute' => 'BÓ 100G',
                'description' => 'Rau thơm tươi, bó 100g.',
                'price' => 25000,
                'image' => 'rau_bo_100g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Thanh năng lượng
            [
                'product_id' => 106,
                'brand' => 'Nature Valley',
                'attribute' => 'THANH 50G',
                'description' => 'Thanh năng lượng Nature Valley, 50g.',
                'price' => 25000,
                'image' => 'thanh_nang_luong_50g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 106,
                'brand' => 'Quest',
                'attribute' => 'THANH 60G',
                'description' => 'Thanh năng lượng Quest, 60g.',
                'price' => 30000,
                'image' => 'thanh_nang_luong_60g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hạt dẻ
            [
                'product_id' => 107,
                'brand' => 'Funtree',
                'attribute' => 'BAO 200G',
                'description' => 'Hạt dẻ rang Funtree, 200g.',
                'price' => 40000,
                'image' => 'hatde_200g.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 107,
                'brand' => 'Nutty',
                'attribute' => 'BAO 250G',
                'description' => 'Hạt dẻ rang Nutty, 250g.',
                'price' => 50000,
                'image' => 'hatde_250g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Khoai tây chiên
            [
                'product_id' => 108,
                'brand' => 'Lay\'s',
                'attribute' => 'GÓI 100G',
                'description' => 'Khoai tây chiên Lay\'s, gói 100g.',
                'price' => 20000,
                'image' => 'lay.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 108,
                'brand' => 'Pringles',
                'attribute' => 'HỘP 150G',
                'description' => 'Khoai tây chiên Pringles, hộp 150g.',
                'price' => 35000,
                'image' => 'pringles.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bắp rang bơ
            [
                'product_id' => 109,
                'brand' => 'Orville Redenbacher\'s',
                'attribute' => 'GÓI 120G',
                'description' => 'Bắp rang bơ Orville, 120g.',
                'price' => 25000,
                'image' => 'bap_120.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 109,
                'brand' => 'Act II',
                'attribute' => 'GÓI 100G',
                'description' => 'Bắp rang bơ Act II, 100g.',
                'price' => 20000,
                'image' => 'bap_100.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh quy
            [
                'product_id' => 110,
                'brand' => 'Oreo',
                'attribute' => 'GÓI 150G',
                'description' => 'Bánh quy Oreo, gói 150g.',
                'price' => 30000,
                'image' => 'oreo.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 110,
                'brand' => 'LU',
                'attribute' => 'GÓI 120G',
                'description' => 'Bánh quy LU, gói 120g.',
                'price' => 25000,
                'image' => 'Lu.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kẹo chocolate
            [
                'product_id' => 111,
                'brand' => 'Mars',
                'attribute' => 'VIÊN 50G',
                'description' => 'Kẹo chocolate Mars, 50g.',
                'price' => 20000,
                'image' => 'mars.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 111,
                'brand' => 'Snickers',
                'attribute' => 'VIÊN 60G',
                'description' => 'Kẹo chocolate Snickers, 60g.',
                'price' => 25000,
                'image' => 'snickers.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kẹo trái cây
            [
                'product_id' => 112,
                'brand' => 'Haribo',
                'attribute' => 'GÓI 100G',
                'description' => 'Kẹo trái cây Haribo, gói 100g.',
                'price' => 20000,
                'image' => 'haribo.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 112,
                'brand' => 'Trolli',
                'attribute' => 'GÓI 120G',
                'description' => 'Kẹo trái cây Trolli, gói 120g.',
                'price' => 25000,
                'image' => 'trolli.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kẹo cao su bạc hà
            [
                'product_id' => 113,
                'brand' => 'Wrigley\'s',
                'attribute' => 'GÓI 10 VIÊN',
                'description' => 'Kẹo cao su Wrigley\'s vị bạc hà, 10 viên.',
                'price' => 15000,
                'image' => 'Wrigley.jpg',
                'quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 113,
                'brand' => 'Extra',
                'attribute' => 'GÓI 12 VIÊN',
                'description' => 'Kẹo cao su Extra vị bạc hà, 12 viên.',
                'price' => 18000,
                'image' => 'extra.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Snack hạt hỗn hợp
            [
                'product_id' => 114,
                'brand' => 'Planters',
                'attribute' => 'GÓI 150G',
                'description' => 'Snack hạt hỗn hợp Planters, 150g.',
                'price' => 40000,
                'image' => 'snack_150g.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 114,
                'brand' => 'Funtree',
                'attribute' => 'GÓI 200G',
                'description' => 'Snack hạt hỗn hợp Funtree, 200g.',
                'price' => 50000,
                'image' => 'snack_200g.jpg',
                'quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh ngọt
            [
                'product_id' => 115,
                'brand' => 'Tous Les Jours',
                'attribute' => 'CÁI 1',
                'description' => 'Bánh ngọt Tous Les Jours, 1 cái.',
                'price' => 30000,
                'image' => 'banh_tous.jpg',
                'quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 115,
                'brand' => 'Paris Baguette',
                'attribute' => 'CÁI 1',
                'description' => 'Bánh ngọt Paris Baguette, 1 cái.',
                'price' => 35000,
                'image' => 'banh_paris.jpg',
                'quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bánh kem
            [
                'product_id' => 116,
                'brand' => 'ABC Bakery',
                'attribute' => 'CÁI 500G',
                'description' => 'Bánh kem ABC Bakery, 500g.',
                'price' => 200000,
                'image' => 'banhkem_abc.jpg',
                'quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 116,
                'brand' => 'XYZ Bakery',
                'attribute' => 'CÁI 700G',
                'description' => 'Bánh kem XYZ Bakery, 700g.',
                'price' => 280000,
                'image' => 'banhkem_xyz.jpg',
                'quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
